{
  "hash": "e669e42f8d6f0b01b6426ad93ff995bf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multinomial logistic regression\"\ntoc: true\nnumber-sections: true\n---\n\n# Why a multinomial model?\n\nThe binary outcome used earlier distinguishes low/no-to-mild post-treatment severity from moderate-or-worse severity. Sometimes the question concerns how treatment redistributes probability across **three or more unordered outcome categories**.\n\nWe use these teaching categories:\n\n- `low_no_to_mild`: LSAS < 50;\n- `moderate_marked`: 50 ≤ LSAS < 80; and\n- `severe_very_severe`: LSAS ≥ 80.\n\nThey are a pedagogical severity grouping, not validated diagnostic or remission thresholds.\n\n# Long data for `mlogit`\n\n`mlogit` represents a multinomial outcome as a choice among alternatives. Each participant therefore appears once for every possible severity category. One and only one alternative is marked as the observed outcome.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(here)\nlibrary(mlogit)\nlibrary(marginaleffects)\n\ndf_outcome <- read_csv2(here(\"data\", \"steps_clean.csv\")) |>\n  filter(!is.na(lsas_post), !is.na(trt)) |>\n  mutate(\n    severity_observed = case_when(\n      lsas_post < 50 ~ \"low_no_to_mild\",\n      lsas_post < 80 ~ \"moderate_marked\",\n      TRUE ~ \"severe_very_severe\"\n    ),\n    severity_observed = factor(\n      severity_observed,\n      levels = c(\"low_no_to_mild\", \"moderate_marked\", \"severe_very_severe\")\n    ),\n    trt = factor(trt,\n      levels = c(\"waitlist\", \"therapist-guided\", \"self-guided\")\n    )\n  ) |>\n  select(id, trt, severity_observed)\n\nlong <- crossing(\n  df_outcome,\n  severity_alt = levels(df_outcome$severity_observed)\n) |>\n  mutate(choice = severity_alt == severity_observed)\n\nlong |>\n  count(id) |>\n  count(n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n      n    nn\n  <int> <int>\n1     3   169\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlogit_data <- mlogit.data(\n  long,\n  choice = \"choice\",\n  shape = \"long\",\n  chid.var = \"id\",\n  alt.var = \"severity_alt\",\n  drop.index = TRUE\n)\n```\n:::\n\n\n# Fit a treatment model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_multinomial <- mlogit(\n  choice ~ 1 | trt,\n  data = mlogit_data,\n  reflevel = \"low_no_to_mild\"\n)\nsummary(mod_multinomial)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nmlogit(formula = choice ~ 1 | trt, data = mlogit_data, reflevel = \"low_no_to_mild\", \n    method = \"nr\")\n\nFrequencies of alternatives:choice\n    low_no_to_mild    moderate_marked severe_very_severe \n           0.25444            0.46746            0.27811 \n\nnr method\n5 iterations, 0h:0m:0s \ng'(-H)^-1g = 1.13E-05 \nsuccessive function values within tolerance limits \n\nCoefficients :\n                                       Estimate Std. Error z-value  Pr(>|z|)\n(Intercept):moderate_marked             1.50408    0.45134  3.3325 0.0008607\n(Intercept):severe_very_severe          1.42712    0.45461  3.1392 0.0016939\ntrttherapist-guided:moderate_marked    -1.41707    0.53928 -2.6277 0.0085967\ntrttherapist-guided:severe_very_severe -2.43872    0.61410 -3.9712 7.151e-05\ntrtself-guided:moderate_marked         -0.87992    0.55325 -1.5905 0.1117305\ntrtself-guided:severe_very_severe      -1.49611    0.58716 -2.5480 0.0108335\n                                          \n(Intercept):moderate_marked            ***\n(Intercept):severe_very_severe         ** \ntrttherapist-guided:moderate_marked    ** \ntrttherapist-guided:severe_very_severe ***\ntrtself-guided:moderate_marked            \ntrtself-guided:severe_very_severe      *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nLog-Likelihood: -169.37\nMcFadden R^2:  0.05419 \nLikelihood ratio test : chisq = 19.409 (p.value = 0.00065319)\n```\n\n\n:::\n:::\n\n\nThe coefficient table uses log-odds contrasts against the reference severity category. We will instead focus on model-based probabilities for each outcome category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Supply the ordinary long data frame, rather than mlogit_data, to\n# marginaleffects when requesting predictions.\nseverity_probabilities <- avg_predictions(\n  mod_multinomial,\n  newdata = as.data.frame(long),\n  by = \"trt\"\n)\nseverity_probabilities\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n              Group              trt Estimate Std. Error    z Pr(>|z|)    S\n low_no_to_mild     waitlist            0.103     0.0400 2.59  0.00968  6.7\n low_no_to_mild     therapist-guided    0.407     0.0669 6.09  < 0.001 29.7\n low_no_to_mild     self-guided         0.263     0.0583 4.51  < 0.001 17.2\n moderate_marked    waitlist            0.466     0.0655 7.11  < 0.001 39.6\n moderate_marked    therapist-guided    0.444     0.0676 6.57  < 0.001 34.2\n moderate_marked    self-guided         0.491     0.0662 7.42  < 0.001 42.9\n severe_very_severe waitlist            0.431     0.0650 6.63  < 0.001 34.8\n severe_very_severe therapist-guided    0.148     0.0483 3.06  0.00218  8.8\n severe_very_severe self-guided         0.246     0.0570 4.31  < 0.001 15.9\n  2.5 % 97.5 %\n 0.0251  0.182\n 0.2764  0.538\n 0.1488  0.377\n 0.3371  0.594\n 0.3119  0.577\n 0.3614  0.621\n 0.3036  0.558\n 0.0534  0.243\n 0.1339  0.357\n\nType: response\n```\n\n\n:::\n:::\n\n\n## Probability redistribution\n\nThe following custom hypothesis calculates therapist-guided minus waitlist probability differences separately for each severity category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntherapist_minus_waitlist <- function(x) {\n  x |>\n    group_by(.data$group, .data$trt) |>\n    summarize(estimate = mean(.data$estimate), .groups = \"drop\") |>\n    pivot_wider(names_from = \"trt\", values_from = \"estimate\") |>\n    transmute(\n      term = .data$group,\n      estimate = .data[[\"therapist-guided\"]] - .data$waitlist\n    )\n}\n\nseverity_differences <- predictions(\n  mod_multinomial,\n  newdata = as.data.frame(long),\n  hypothesis = therapist_minus_waitlist\n)\nseverity_differences\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n               Term Estimate Std. Error      z Pr(>|z|)    S  2.5 % 97.5 %\n low_no_to_mild       0.3040     0.0779  3.901   <0.001 13.4  0.151  0.457\n moderate_marked     -0.0211     0.0941 -0.224    0.823  0.3 -0.206  0.163\n severe_very_severe  -0.2829     0.0810 -3.491   <0.001 11.0 -0.442 -0.124\n\nType: response\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Model interpretation\n\nCompared with waitlist, therapist-guided treatment changes the estimated probability of low/no-to-mild severity by **30.4 percentage points** (95% CI **15.1** to **45.7 percentage points**).\n\nThe probability of severe/very severe symptoms changes by **-28.3 percentage points** (95% CI **-44.2** to **-12.4 percentage points**). The category probabilities must sum to one, so an increase in one category is accompanied by decreases elsewhere.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseverity_probabilities |>\n  ggplot(aes(x = trt, y = estimate, color = group, group = group)) +\n  geom_point(position = position_dodge(width = .2)) +\n  geom_errorbar(\n    aes(ymin = conf.low, ymax = conf.high),\n    width = .1,\n    position = position_dodge(width = .2)\n  ) +\n  labs(\n    title = \"Estimated post-treatment severity probabilities\",\n    subtitle = \"Multinomial logit; 95% confidence intervals\",\n    x = \"Treatment group\",\n    y = \"Estimated probability\",\n    color = \"Severity category\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](multinomial-logit_files/figure-html/plot-multinomial-probabilities-1.png){width=672}\n:::\n:::\n\n\n# Summary\n\n- Multinomial logit models probabilities for multiple outcome categories.\n- `mlogit` needs a long participant-by-alternative data structure.\n- Interpret the model as a redistribution of outcome probabilities, not as isolated coefficient changes.\n- The probability differences for the categories sum to zero across any treatment contrast.\n",
    "supporting": [
      "multinomial-logit_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}