{
  "hash": "1de44bee09540d1eceff3e6bd308b7b7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic regression with two binary predictors\"\nformat:\n  html:\n    df-print: kable\ntoc: true\ntoc-depth: 3\nnumber-sections: true\n---\n\n# Two predictors, one clinical question\n\nThe previous logistic-regression chapters considered one predictor at a time. Clinical questions often ask whether a treatment contrast looks different in a baseline subgroup. Here we model the probability of a **treatment response** using:\n\n- treatment group (`trt`); and\n- a binary baseline PHQ-9 category (`phq_cat`).\n\nOur teaching question is:\n\n> Within each PHQ-9 category, how does the estimated probability of treatment response differ between therapist-guided treatment and waitlist?\n\nWe will first fit an additive logistic model and then a model with `trt * phq_cat`. The probability difference, with its 95% confidence interval, is the clinical contrast. Log-odds and odds ratios help us read model output and research papers, but neither is a percentage-point difference.\n\n# Packages and data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(here)\nlibrary(broom)\nlibrary(marginaleffects)\n\noptions(\n  marginaleffects_print_omit = c(\"s.value\"),\n  marginaleffects_print_style = ifelse(interactive(), \"summary\", \"tinytable\")\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_binary <- read_csv2(here(\"..\", \"..\", \"data\", \"steps_clean.csv\")) |>\n  filter(!is.na(lsas_screen), !is.na(lsas_post)) |>\n  mutate(\n    # The second outcome level is the event modelled by binomial glm().\n    lsas_response = factor(\n      if_else((lsas_screen - lsas_post) / lsas_screen >= 0.30, \"Response\", \"No response\"),\n      levels = c(\"No response\", \"Response\")\n    ),\n    trt = factor(\n      trt,\n      levels = c(\"waitlist\", \"therapist-guided\", \"self-guided\")\n    ),\n    phq_cat = factor(\n      case_when(\n        phq9_screen < 10 ~ \"< 10\",\n        phq9_screen >= 10 ~ \">= 10\"\n      ),\n      levels = c(\"< 10\", \">= 10\")\n    )\n  )|>\n  filter(trt %in% c(\"waitlist\", \"therapist-guided\")) |>\n  droplevels()\n\ndf_binary |>\n  count(phq_cat, lsas_response, .drop = FALSE)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|phq_cat |lsas_response |  n|\n|:-------|:-------------|--:|\n|< 10    |No response   | 40|\n|< 10    |Response      | 21|\n|>= 10   |No response   | 35|\n|>= 10   |Response      | 16|\n\n</div>\n:::\n:::\n\n\n`phq_cat` explicitly divides baseline PHQ-9 scores into `< 10` and `>= 10`. It is a convenient binary moderator for this lesson, not a claim that these two groups are biologically distinct or that a subgroup result is clinically established. The outcome is treatment response, defined as a reduction of at least 30% from baseline LSAS.\n\nWaitlist is the reference treatment group, `< 10` is the reference PHQ-9 category, and `Low` is the modelled outcome event.\n\n# Additive logistic model\n\nAn additive model has treatment and PHQ-9-category terms but no product term:\n\n$$\n\\operatorname{logit}\\left[P(Y_i = \\mathrm{Response})\\right]\n=\n\\beta_0 + \\beta_1 trt_i + \\beta_2 phq_i\n$$\n\nOn the **log-odds scale**, this model says that the treatment odds ratio is the same in both PHQ-9 categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_additive <- stats::glm(\n  lsas_response ~ trt + phq_cat,\n  family = binomial,\n  data = df_binary\n)\n\nsummary(mod_additive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nstats::glm(formula = lsas_response ~ trt + phq_cat, family = binomial, \n    data = df_binary)\n\nCoefficients:\n                    Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         -2.14895    0.48573  -4.424 9.68e-06 ***\ntrttherapist-guided  2.45679    0.51206   4.798 1.60e-06 ***\nphq_cat>= 10        -0.02193    0.46766  -0.047    0.963    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 142.11  on 111  degrees of freedom\nResidual deviance: 112.25  on 109  degrees of freedom\nAIC: 118.25\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nWe can get the OR of both therapist-guided vs waitlist and PHQ-9 high vs low by exponentiating the coefficients. Because the additive model does not allow for interactions on the log-odds or odds scale, the OR between the treatment groups are forced to be the same, regardless of PHQ-9 score.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(2.45679) # odds ratio therapist-guided vs waitlist\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11.6673\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(-0.02193) # odds ratio >= 10 vs <10 on PHQ-9\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9783087\n```\n\n\n:::\n:::\n\n\nThe fact that the odds ratio is the same in both PHQ-9 categories does *not* guarantee identical probability differences: changing a probability by a fixed odds ratio can produce different percentage-point changes at different baseline probabilities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadditive_probabilities <- avg_predictions(\n  mod_additive,\n  by = c(\"trt\", \"phq_cat\"),\n  type = \"response\"\n)\n\nadditive_treatment_effects <- avg_comparisons(\n  mod_additive,\n  variables = list(trt = c(\"waitlist\", \"therapist-guided\")),\n  by = \"phq_cat\",\n  type = \"response\"\n)\n\nadditive_treatment_low_phq <- additive_treatment_effects |>\n  filter(phq_cat == \"< 10\")\nadditive_treatment_high_phq <- additive_treatment_effects |>\n  filter(phq_cat == \">= 10\")\n\nadditive_odds_ratio <- tidy(\n  mod_additive,\n  conf.int = TRUE,\n  exponentiate = TRUE\n) |>\n  filter(term == \"trttherapist-guided\")\n\nadditive_probabilities\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_2i7s25w1b64r2sx7lbjz = TinyTable.createTableFunctions(\"tinytable_2i7s25w1b64r2sx7lbjz\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '4', j: 1 }, { i: '4', j: 2 }, { i: '4', j: 3 }, { i: '4', j: 4 }, { i: '4', j: 5 }, { i: '4', j: 6 }, { i: '4', j: 7 }, { i: '4', j: 8 } ], css_id: 'tinytable_css_9csnmvvhxr0bi49mq8yq',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 }, { i: '0', j: 8 } ], css_id: 'tinytable_css_j3f4zgbv5cggfcvj96hq',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_2i7s25w1b64r2sx7lbjz.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_2i7s25w1b64r2sx7lbjz td.tinytable_css_9csnmvvhxr0bi49mq8yq, #tinytable_2i7s25w1b64r2sx7lbjz th.tinytable_css_9csnmvvhxr0bi49mq8yq {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_2i7s25w1b64r2sx7lbjz td.tinytable_css_j3f4zgbv5cggfcvj96hq, #tinytable_2i7s25w1b64r2sx7lbjz th.tinytable_css_j3f4zgbv5cggfcvj96hq {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_2i7s25w1b64r2sx7lbjz\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">trt</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">phq_cat</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Estimate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Std. Error</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">z</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">Pr(&gt;|z|)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">2.5 %</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"8\">97.5 %</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='8'>Type: response</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">waitlist</td>\n                  <td data-row=\"1\" data-col=\"2\">&lt; 10</td>\n                  <td data-row=\"1\" data-col=\"3\">0.104</td>\n                  <td data-row=\"1\" data-col=\"4\">0.0454</td>\n                  <td data-row=\"1\" data-col=\"5\">2.30</td>\n                  <td data-row=\"1\" data-col=\"6\">0.0215</td>\n                  <td data-row=\"1\" data-col=\"7\">0.0154</td>\n                  <td data-row=\"1\" data-col=\"8\">0.193</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">waitlist</td>\n                  <td data-row=\"2\" data-col=\"2\">&gt;= 10</td>\n                  <td data-row=\"2\" data-col=\"3\">0.102</td>\n                  <td data-row=\"2\" data-col=\"4\">0.0455</td>\n                  <td data-row=\"2\" data-col=\"5\">2.25</td>\n                  <td data-row=\"2\" data-col=\"6\">0.0245</td>\n                  <td data-row=\"2\" data-col=\"7\">0.0132</td>\n                  <td data-row=\"2\" data-col=\"8\">0.192</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">therapist-guided</td>\n                  <td data-row=\"3\" data-col=\"2\">&lt; 10</td>\n                  <td data-row=\"3\" data-col=\"3\">0.576</td>\n                  <td data-row=\"3\" data-col=\"4\">0.0830</td>\n                  <td data-row=\"3\" data-col=\"5\">6.94</td>\n                  <td data-row=\"3\" data-col=\"6\">&lt;0.001</td>\n                  <td data-row=\"3\" data-col=\"7\">0.4137</td>\n                  <td data-row=\"3\" data-col=\"8\">0.739</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">therapist-guided</td>\n                  <td data-row=\"4\" data-col=\"2\">&gt;= 10</td>\n                  <td data-row=\"4\" data-col=\"3\">0.571</td>\n                  <td data-row=\"4\" data-col=\"4\">0.0941</td>\n                  <td data-row=\"4\" data-col=\"5\">6.07</td>\n                  <td data-row=\"4\" data-col=\"6\">&lt;0.001</td>\n                  <td data-row=\"4\" data-col=\"7\">0.3865</td>\n                  <td data-row=\"4\" data-col=\"8\">0.755</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n\n```{.r .cell-code}\nadditive_treatment_effects\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_tu8lbqb0v2s8taibzpgb = TinyTable.createTableFunctions(\"tinytable_tu8lbqb0v2s8taibzpgb\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 1 }, { i: '2', j: 2 }, { i: '2', j: 3 }, { i: '2', j: 4 }, { i: '2', j: 5 }, { i: '2', j: 6 }, { i: '2', j: 7 } ], css_id: 'tinytable_css_sep33b05z38pgv5fp855',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_4iynlepn1p078pmgtx5d',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_tu8lbqb0v2s8taibzpgb.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_tu8lbqb0v2s8taibzpgb td.tinytable_css_sep33b05z38pgv5fp855, #tinytable_tu8lbqb0v2s8taibzpgb th.tinytable_css_sep33b05z38pgv5fp855 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_tu8lbqb0v2s8taibzpgb td.tinytable_css_4iynlepn1p078pmgtx5d, #tinytable_tu8lbqb0v2s8taibzpgb th.tinytable_css_4iynlepn1p078pmgtx5d {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_tu8lbqb0v2s8taibzpgb\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">phq_cat</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Estimate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Std. Error</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">z</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Pr(&gt;|z|)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">2.5 %</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">97.5 %</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='7'>Term: trt</td></tr>\n<tr><td colspan='7'>Comparison: therapist-guided - waitlist</td></tr>\n<tr><td colspan='7'>Type: response</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">&lt; 10</td>\n                  <td data-row=\"1\" data-col=\"2\">0.472</td>\n                  <td data-row=\"1\" data-col=\"3\">0.0832</td>\n                  <td data-row=\"1\" data-col=\"4\">5.68</td>\n                  <td data-row=\"1\" data-col=\"5\">&lt;0.001</td>\n                  <td data-row=\"1\" data-col=\"6\">0.309</td>\n                  <td data-row=\"1\" data-col=\"7\">0.635</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">&gt;= 10</td>\n                  <td data-row=\"2\" data-col=\"2\">0.469</td>\n                  <td data-row=\"2\" data-col=\"3\">0.0894</td>\n                  <td data-row=\"2\" data-col=\"4\">5.24</td>\n                  <td data-row=\"2\" data-col=\"5\">&lt;0.001</td>\n                  <td data-row=\"2\" data-col=\"6\">0.293</td>\n                  <td data-row=\"2\" data-col=\"7\">0.644</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Model interpretation\n\nCompared with waitlist, therapist-guided treatment has an estimated probability of treatment response that is **higher by 47.2 percentage points** among participants with baseline PHQ-9 `< 10` (95% CI **30.9 to 63.5 percentage points**). Among participants with baseline PHQ-9 `>= 10`, it is **higher by 46.9 percentage points** (95% CI **29.3 to 64.4 percentage points**).\n\nBecause this is an additive *logistic* model, its therapist-guided-versus-waitlist odds ratio is **11.67** (95% CI **4.53 to 34.62**) in both PHQ-9 categories, adjusted for PHQ-9 category. This is a ratio of odds, not a percentage-point probability change; the conditional probability differences above are the primary results.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_predictions(\n  mod_additive,\n  by = c(\"trt\", \"phq_cat\"),\n  type = \"response\"\n) +\n  labs(\n    title = \"Additive logistic model\",\n    subtitle = \"Estimated probabilities by treatment and baseline PHQ-9 category\",\n    x = \"Treatment group\",\n    y = \"Estimated probability of treatment response (95% CI)\",\n    colour = \"Baseline PHQ-9\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Additive-model estimated probabilities of treatment response. Error bars are 95% confidence intervals.](logistic-two-binary-predictors_files/figure-html/plot-additive-probabilities-1.png){width=672}\n:::\n:::\n\n\n# Interaction model\n\nThe interaction model uses the requested product term, `trt * phq_cat`:\n\n$$\n\\operatorname{logit}\\left[P(Y_i = \\mathrm{Response})\\right]\n=\n\\beta_0 + \\beta_1 trt_i + \\beta_2 phq_i\n+ \\beta_3(trt_i \\times phq_i).\n$$\n\nThe interaction terms let treatment associations with the outcome differ by baseline PHQ-9 category. Since both trt and phq_cat are binary (0/1), the only combination that does not become 0 is when both are 1 (i.e. when trt = therapist-guided group and phq_cat = \\>= 10). The treatment main-effect coefficients are now interpreted at the reference category, PHQ-9 `< 10`; they are not an overall treatment effect.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_interaction <- stats::glm(\n  lsas_response ~ trt * phq_cat,\n  family = binomial,\n  data = df_binary\n)\n\nsummary(mod_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nstats::glm(formula = lsas_response ~ trt * phq_cat, family = binomial, \n    data = df_binary)\n\nCoefficients:\n                                 Estimate Std. Error z value Pr(>|z|)    \n(Intercept)                      -2.19722    0.60853  -3.611 0.000305 ***\ntrttherapist-guided               2.52265    0.70908   3.558 0.000374 ***\nphq_cat>= 10                      0.07696    0.86233   0.089 0.928885    \ntrttherapist-guided:phq_cat>= 10 -0.14002    1.02617  -0.136 0.891466    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 142.11  on 111  degrees of freedom\nResidual deviance: 112.23  on 108  degrees of freedom\nAIC: 120.23\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nWe can exponentiate the coefficients to express them on the odds-ratio scale. In an interaction model, however, the treatment coefficient now represents the treatment effect when PHQ-9 is in its reference category (\\< 10). Thus, $\\exp(2.52265)$ is the OR for therapist-guided treatment versus waitlist among participants with PHQ-9 \\< 10.\n\nThe interaction coefficient tells us how the treatment OR changes when moving from PHQ-9 \\< 10 to PHQ-9 ≥ 10. Here, $\\exp(-0.14002)$ is the ratio of the two treatment ORs. To obtain the treatment OR among participants with PHQ-9 ≥ 10, we therefore combine the treatment and interaction coefficients: $\\exp(2.52265 - 0.14002)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(2.52265)                 # treatment OR when PHQ-9 < 10\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12.46158\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(-0.14002)                # ratio of treatment ORs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8693408\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(2.52265 - 0.14002)       # treatment OR when PHQ-9 >= 10\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.83336\n```\n\n\n:::\n:::\n\n\nTo go from the odds scale to the probability scale, we can again use functions from the `marginaleffects` package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninteraction_probabilities <- avg_predictions(\n  mod_interaction,\n  by = c(\"trt\", \"phq_cat\"),\n  type = \"response\"\n)\n\ninteraction_probabilities\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_u1ekwopg98fmlxx6mss4 = TinyTable.createTableFunctions(\"tinytable_u1ekwopg98fmlxx6mss4\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '4', j: 1 }, { i: '4', j: 2 }, { i: '4', j: 3 }, { i: '4', j: 4 }, { i: '4', j: 5 }, { i: '4', j: 6 }, { i: '4', j: 7 }, { i: '4', j: 8 } ], css_id: 'tinytable_css_fs6t62hnwmlnxgnjy8qu',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 }, { i: '0', j: 8 } ], css_id: 'tinytable_css_g8w0dqqhopqwfn5e84c1',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_u1ekwopg98fmlxx6mss4.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_u1ekwopg98fmlxx6mss4 td.tinytable_css_fs6t62hnwmlnxgnjy8qu, #tinytable_u1ekwopg98fmlxx6mss4 th.tinytable_css_fs6t62hnwmlnxgnjy8qu {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_u1ekwopg98fmlxx6mss4 td.tinytable_css_g8w0dqqhopqwfn5e84c1, #tinytable_u1ekwopg98fmlxx6mss4 th.tinytable_css_g8w0dqqhopqwfn5e84c1 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_u1ekwopg98fmlxx6mss4\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">trt</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">phq_cat</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Estimate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Std. Error</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">z</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">Pr(&gt;|z|)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">2.5 %</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"8\">97.5 %</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='8'>Type: response</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">waitlist</td>\n                  <td data-row=\"1\" data-col=\"2\">&lt; 10</td>\n                  <td data-row=\"1\" data-col=\"3\">0.100</td>\n                  <td data-row=\"1\" data-col=\"4\">0.0548</td>\n                  <td data-row=\"1\" data-col=\"5\">1.83</td>\n                  <td data-row=\"1\" data-col=\"6\">0.0679</td>\n                  <td data-row=\"1\" data-col=\"7\">-0.00734</td>\n                  <td data-row=\"1\" data-col=\"8\">0.207</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">waitlist</td>\n                  <td data-row=\"2\" data-col=\"2\">&gt;= 10</td>\n                  <td data-row=\"2\" data-col=\"3\">0.107</td>\n                  <td data-row=\"2\" data-col=\"4\">0.0584</td>\n                  <td data-row=\"2\" data-col=\"5\">1.83</td>\n                  <td data-row=\"2\" data-col=\"6\">0.0668</td>\n                  <td data-row=\"2\" data-col=\"7\">-0.00742</td>\n                  <td data-row=\"2\" data-col=\"8\">0.222</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">therapist-guided</td>\n                  <td data-row=\"3\" data-col=\"2\">&lt; 10</td>\n                  <td data-row=\"3\" data-col=\"3\">0.581</td>\n                  <td data-row=\"3\" data-col=\"4\">0.0886</td>\n                  <td data-row=\"3\" data-col=\"5\">6.55</td>\n                  <td data-row=\"3\" data-col=\"6\">&lt;0.001</td>\n                  <td data-row=\"3\" data-col=\"7\">0.40694</td>\n                  <td data-row=\"3\" data-col=\"8\">0.754</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">therapist-guided</td>\n                  <td data-row=\"4\" data-col=\"2\">&gt;= 10</td>\n                  <td data-row=\"4\" data-col=\"3\">0.565</td>\n                  <td data-row=\"4\" data-col=\"4\">0.1034</td>\n                  <td data-row=\"4\" data-col=\"5\">5.47</td>\n                  <td data-row=\"4\" data-col=\"6\">&lt;0.001</td>\n                  <td data-row=\"4\" data-col=\"7\">0.36262</td>\n                  <td data-row=\"4\" data-col=\"8\">0.768</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n\n```{.r .cell-code}\ninteraction_treatment_effects <- avg_comparisons(\n  mod_interaction,\n  variables = list(trt = c(\"waitlist\", \"therapist-guided\")),\n  by = \"phq_cat\",\n  type = \"response\"\n)\n\ninteraction_treatment_effects\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_cvpen2ua8zxk21h6of4c = TinyTable.createTableFunctions(\"tinytable_cvpen2ua8zxk21h6of4c\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 1 }, { i: '2', j: 2 }, { i: '2', j: 3 }, { i: '2', j: 4 }, { i: '2', j: 5 }, { i: '2', j: 6 }, { i: '2', j: 7 } ], css_id: 'tinytable_css_1weej9sgdfp01oko2djz',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_384x46y64fqf0fz2art7',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_cvpen2ua8zxk21h6of4c.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_cvpen2ua8zxk21h6of4c td.tinytable_css_1weej9sgdfp01oko2djz, #tinytable_cvpen2ua8zxk21h6of4c th.tinytable_css_1weej9sgdfp01oko2djz {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_cvpen2ua8zxk21h6of4c td.tinytable_css_384x46y64fqf0fz2art7, #tinytable_cvpen2ua8zxk21h6of4c th.tinytable_css_384x46y64fqf0fz2art7 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_cvpen2ua8zxk21h6of4c\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">phq_cat</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Estimate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Std. Error</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">z</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Pr(&gt;|z|)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">2.5 %</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">97.5 %</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='7'>Term: trt</td></tr>\n<tr><td colspan='7'>Comparison: therapist-guided - waitlist</td></tr>\n<tr><td colspan='7'>Type: response</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">&lt; 10</td>\n                  <td data-row=\"1\" data-col=\"2\">0.481</td>\n                  <td data-row=\"1\" data-col=\"3\">0.104</td>\n                  <td data-row=\"1\" data-col=\"4\">4.61</td>\n                  <td data-row=\"1\" data-col=\"5\">&lt;0.001</td>\n                  <td data-row=\"1\" data-col=\"6\">0.276</td>\n                  <td data-row=\"1\" data-col=\"7\">0.685</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">&gt;= 10</td>\n                  <td data-row=\"2\" data-col=\"2\">0.458</td>\n                  <td data-row=\"2\" data-col=\"3\">0.119</td>\n                  <td data-row=\"2\" data-col=\"4\">3.86</td>\n                  <td data-row=\"2\" data-col=\"5\">&lt;0.001</td>\n                  <td data-row=\"2\" data-col=\"6\">0.225</td>\n                  <td data-row=\"2\" data-col=\"7\">0.691</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Model interpretation\n\nWithin the baseline PHQ-9 `< 10` category, therapist-guided treatment has an estimated probability of treatment response that is **higher by 48.1 percentage points** than waitlist (95% CI **27.6 to 68.5 percentage points**). Within the baseline PHQ-9 `>= 10` category, the corresponding probability is **higher by 45.8 percentage points** (95% CI **22.5 to 69.1 percentage points**).\n\nThe associated therapist-guided-versus-waitlist odds ratios are **12.46** (95% CI **3.10 to 50.02**) for PHQ-9 `< 10` and **10.83** (95% CI **2.53 to 46.36**) for PHQ-9 `>= 10`. They compare odds, not probabilities. Use the conditional probability differences above—not these odds ratios—to describe the clinical contrast.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninteraction_probabilities |>\n  ggplot(aes(x = trt, y = estimate, group = phq_cat, colour = phq_cat)) +\n  geom_point(position = position_dodge(width = 0.1)) +\n  geom_line(position = position_dodge(width = 0.1)) +\n  geom_errorbar(\n    aes(ymin = conf.low, ymax = conf.high),\n    width = 0.1,\n    position = position_dodge(width = 0.1)\n  ) +\n  labs(\n    title = \"Interaction logistic model\",\n    subtitle = \"Treatment probabilities may differ by baseline PHQ-9 category\",\n    x = \"Treatment group\",\n    y = \"Estimated probability of treatment response (95% CI)\",\n    colour = \"Baseline PHQ-9\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Interaction-model estimated probabilities of treatment response. Error bars are 95% confidence intervals.](logistic-two-binary-predictors_files/figure-html/plot-interaction-probabilities-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_comparisons(\n  mod_interaction,\n  variables = list(trt = c(\"waitlist\", \"therapist-guided\")),\n  by = \"phq_cat\",\n  type = \"response\"\n) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  labs(\n    title = \"Conditional treatment effects on the probability scale\",\n    x = \"Baseline PHQ-9 category\",\n    y = \"Therapist-guided minus waitlist probability difference (95% CI)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Conditional therapist-guided-minus-waitlist probability differences from the interaction model. Error bars are 95% confidence intervals.](logistic-two-binary-predictors_files/figure-html/plot-conditional-treatment-effects-1.png){width=672}\n:::\n:::\n\n\n# Interpreting the interaction\n\nAn interaction model can describe different conditional estimates, but it does not automatically establish a clinically meaningful subgroup. Before presenting a subgroup finding, ask:\n\n1.  Was the moderator and interaction planned before looking at the data?\n2.  Are the conditional probability differences precise enough to distinguish meaningful patterns from sampling variation?\n3.  Does the interaction plot show a consistent, clinically interpretable pattern rather than an isolated coefficient or p-value?\n4.  Would the conclusion be different if PHQ-9 were modelled continuously? See [logistic regression with a binary and numeric predictor](logistic-binary-numeric-predictors.qmd).\n\nThe interaction coefficient is a difference of **log-odds contrasts**. It is not itself the difference between the two probability differences. `avg_comparisons()` gives the quantities we want to communicate: therapist-guided-minus-waitlist probability differences within the explicitly stated PHQ-9 categories.\n\n# Summary\n\nIn this chapter you learned to:\n\n- derive `phq_cat` explicitly as baseline PHQ-9 `< 10` versus `>= 10`;\n- fit additive and `trt * phq_cat` binary logistic models with `stats::glm(..., family = binomial)`;\n- report treatment contrasts as conditional probability differences in percentage points with 95% CIs;\n- distinguish a conditional odds ratio from a probability difference; and\n- use predicted-probability and conditional-effect plots to inspect a proposed subgroup pattern.\n",
    "supporting": [
      "logistic-two-binary-predictors_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}