project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - chapters/*.qmd
    - labs/*.qmd

execute:
  freeze: auto

bibliography: references.bib

website:
  title: "Biostatistics - Research School in Clinical Psychiatry"
  page-navigation: true
  repo-url: https://github.com/biostatistics-psychiatry/lab-materials
  repo-actions: [edit, issue]

  sidebar:
    title: "Biostatistics - III"
    pinned: true
    align: center

    style: docked
    search: true
    collapse-level: 1

    contents:
      - section: "Course information"
        contents:
          - href: index.qmd
            text: Overview

      - section: "Chapters"
        contents:
          - href: chapters/logistic-intro.qmd
            text: Logistic-regression foundations
          - href: chapters/logistic-one-binary-predictor.qmd
            text: Logistic regression with a binary predictor
          - href: chapters/logistic-one-categorical-predictor.qmd
            text: Logistic regression with a categorical predictor
          - href: chapters/logistic-one-numeric-predictor.qmd
            text: Logistic regression with a numeric predictor
          - href: chapters/multinomial-logit.qmd
            text: Multinomial logistic regression
          - href: chapters/logistic-two-binary-predictors.qmd
            text: Logistic regression with two binary predictors
          - href: chapters/logistic-binary-numeric-predictors.qmd
            text: Logistic regression with a binary and numeric predictor

      - section: "Labs"
        contents:
          - href: labs/lab-logistic-foundations.qmd
            text: Logistic-regression foundations
          - href: labs/lab-categorical-predictors.qmd
            text: Logistic regression with binary and categorical predictors
          - href: labs/lab-multinomial-logit.qmd
            text: Multinomial logistic regression
          - href: labs/lab-binary-interactions.qmd
            text: Logistic regression with two binary predictors
          - href: labs/lab-continuous-interactions.qmd
            text: Logistic regression with a binary and numeric predictor


format:
  html:
    theme: flatly
    toc: true
    toc-depth: 6
    crossref:
      custom:
        - kind: float
          reference-prefix: "Exercise"
          key: "exr"
