{
  "hash": "11de468ebd27a9e1bc0c929f0f6f3355",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic regression with a binary predictor\"\nformat:\n  html:\n    df-print: kable\ntoc: true\ntoc-depth: 3\nnumber-sections: true\neditor: \n  markdown: \n    wrap: 72\n---\n\n# Introduction\n\nThis notebook extends the treatment example from [logistic-regression\nfoundations](logistic-intro.qmd). We focus on the two arms that make a\nbinary treatment predictor: `waitlist` and `therapist-guided`.\n\nOur question is:\n\n> Among participants in these two arms, how does the estimated\n> probability of treatment response differ for therapist-guided\n> treatment versus waitlist?\n\nThe target is the **therapist-guided minus waitlist probability\ndifference**. We will use the corresponding odds ratio to read\nlogistic-regression output, but the probability difference is the\nprimary clinical result.\n\n# Packages and data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(here)\nlibrary(broom)\nlibrary(marginaleffects)\n\noptions(\n  marginaleffects_print_omit = c(\"s.value\"),\n  marginaleffects_print_style = ifelse(interactive(), \"summary\", \"tinytable\")\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_binary <- read_csv2(here(\"..\", \"..\", \"data\", \"steps_clean.csv\")) |>\n  filter(!is.na(lsas_screen), !is.na(lsas_post)) |>\n  mutate(\n    # The second level is the event modelled by binomial glm().\n    lsas_response = factor(\n      if_else((lsas_screen - lsas_post) / lsas_screen >= 0.30, \"Response\", \"No response\"),\n      levels = c(\"No response\", \"Response\")\n    ),\n    trt = factor(\n      trt,\n      levels = c(\"waitlist\", \"therapist-guided\", \"self-guided\")\n    )\n  ) |>\n  filter(trt %in% c(\"waitlist\", \"therapist-guided\")) |>\n  droplevels()\n\ndf_binary |>\n  count(trt, lsas_response, .drop = FALSE)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|trt              |lsas_response |  n|\n|:----------------|:-------------|--:|\n|waitlist         |No response   | 52|\n|waitlist         |Response      |  6|\n|therapist-guided |No response   | 23|\n|therapist-guided |Response      | 31|\n\n</div>\n:::\n:::\n\n\n`Response` means that LSAS decreases by at least 30% from baseline, as\nin [logistic-regression foundations](logistic-intro.qmd).\n\nWe explicitly make waitlist the reference group. The treatment contrast\nshown by the coefficient will therefore be logg-odds of response for the\ntherapist-guided group minus the log-odds for treatment response in the\nwaitlist group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(df_binary$trt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"waitlist\"         \"therapist-guided\"\n```\n\n\n:::\n\n```{.r .cell-code}\ncontrasts(df_binary$trt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 therapist-guided\nwaitlist                        0\ntherapist-guided                1\n```\n\n\n:::\n:::\n\n\n# A logistic model for two treatment groups\n\nFor participant $i$, let $Y_i$ indicate treatment response. The model is\n\n$$\n\\operatorname{logit}\\left[P(Y_i = \\text{Response} \\mid trt_i)\\right] =\n\\beta_0 + \\beta_1\\,\\mathbf{1}\\{trt_i = \\text{therapist-guided}\\}.\n$$\n\nHere, $\\beta_0$ is the log-odds of response in the waitlist group, and\n$\\beta_1$ is the therapist-guided-versus-waitlist log-odds difference.\nThese are the quantities that `glm()` estimates directly. They are not\nyet the most clinically intelligible quantities.\n\n## Fit and interpret the model\n\nWe fit the model using the `glm()` function, with the\n`family = binomial` to tell `R` that this is a logistic model. We can\nthen use the `summary()` function to see the model coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_binary_trt <- stats::glm(\n  lsas_response ~ trt, # model formula\n  family = binomial, # using the binomial family to get a logistic regression\n  data = df_binary # using our dataset df_binary\n)\n\nsummary(mod_binary_trt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nstats::glm(formula = lsas_response ~ trt, family = binomial, \n    data = df_binary)\n\nCoefficients:\n                    Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          -2.1595     0.4311  -5.009 5.48e-07 ***\ntrttherapist-guided   2.4580     0.5115   4.806 1.54e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 142.11  on 111  degrees of freedom\nResidual deviance: 112.25  on 110  degrees of freedom\nAIC: 116.25\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nThe output from `summary()` shows us that the log-odds in the treatment\ngroup is -2.16 and that the log-odds in the therapist-guided group is\n2.46 higher that that of the waitlist (i.e. -2.16 + 2.46).\n\nBy exponentiating the linear predictors (added coefficients), **we get\nthe odds for each group.** By exponentiating only the coefficient for\nthe therapist-guided group (2.46; the difference in log-odds bewteen the\ntherapist-guided and the waitlist group), we get the **odds ratio of\nresponse in the therapist-guided vs. the waitlist group**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(-2.16) # odds of response in waitlist group\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1153251\n```\n\n\n:::\n\n```{.r .cell-code}\nexp( -2.16 + 2.46) # odds of response in therapist-guided group\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.349859\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(2.46) # odds ratio of response in the therapist-guided group vs. the waitlist\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11.70481\n```\n\n\n:::\n:::\n\n\nTo go from the linear predictors of the log-odds to the probability, we\ncan use the inverse logit function:\n\n$$\\operatorname{logit}^{-1}(x) = \\frac{e^x}{1 + e^x}$$\n\n| Treatment group | Linear predictor | Model-derived probability |\n|--------------------|-------------------------:|-------------------------:|\n| waitlist | $\\beta_0$ | $\\operatorname{logit}^{-1}(\\beta_0)$ |\n| therapist-guided | $\\beta_0 + \\beta_1$ | $\\operatorname{logit}^{-1}(\\beta_0 + \\beta_1)$ |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(-2.16)/ (1+exp(-2.16)) # probability of resonse in waitlist group\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1034005\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(-2.16 + 2.46)/ (1+exp(-2.16 + 2.46)) # probability of resonse in therapist group\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5744425\n```\n\n\n:::\n:::\n\n\n## Get probabilities and the probability difference from the model\n\nYou can also get these predicted probabilities using the\n`marginaleffects` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_binary_trt <- avg_predictions(\n  mod_binary_trt,\n  by = \"trt\",\n  type = \"response\"\n)\n\ndiff_binary_trt <- avg_comparisons(\n  mod_binary_trt,\n  variables = list(trt = c(\"waitlist\", \"therapist-guided\")),\n  type = \"response\"\n)\n\nor_binary_trt <- tidy(\n  mod_binary_trt,\n  conf.int = TRUE,\n  exponentiate = TRUE\n) |>\n  filter(term == \"trttherapist-guided\")\n\np_binary_trt\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_06anrm1qdw7uqt5a7jwq = TinyTable.createTableFunctions(\"tinytable_06anrm1qdw7uqt5a7jwq\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 1 }, { i: '2', j: 2 }, { i: '2', j: 3 }, { i: '2', j: 4 }, { i: '2', j: 5 }, { i: '2', j: 6 }, { i: '2', j: 7 } ], css_id: 'tinytable_css_cd05zbd67xlr2wfj1cde',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_pil6fx7nrmyvw8xs0e5t',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_06anrm1qdw7uqt5a7jwq.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_06anrm1qdw7uqt5a7jwq td.tinytable_css_cd05zbd67xlr2wfj1cde, #tinytable_06anrm1qdw7uqt5a7jwq th.tinytable_css_cd05zbd67xlr2wfj1cde {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_06anrm1qdw7uqt5a7jwq td.tinytable_css_pil6fx7nrmyvw8xs0e5t, #tinytable_06anrm1qdw7uqt5a7jwq th.tinytable_css_pil6fx7nrmyvw8xs0e5t {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_06anrm1qdw7uqt5a7jwq\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">trt</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Estimate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Std. Error</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">z</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Pr(&gt;|z|)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">2.5 %</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">97.5 %</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='7'>Type: response</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">waitlist</td>\n                  <td data-row=\"1\" data-col=\"2\">0.103</td>\n                  <td data-row=\"1\" data-col=\"3\">0.0400</td>\n                  <td data-row=\"1\" data-col=\"4\">2.59</td>\n                  <td data-row=\"1\" data-col=\"5\">0.00968</td>\n                  <td data-row=\"1\" data-col=\"6\">0.0251</td>\n                  <td data-row=\"1\" data-col=\"7\">0.182</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">therapist-guided</td>\n                  <td data-row=\"2\" data-col=\"2\">0.574</td>\n                  <td data-row=\"2\" data-col=\"3\">0.0673</td>\n                  <td data-row=\"2\" data-col=\"4\">8.53</td>\n                  <td data-row=\"2\" data-col=\"5\">&lt; 0.001</td>\n                  <td data-row=\"2\" data-col=\"6\">0.4422</td>\n                  <td data-row=\"2\" data-col=\"7\">0.706</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n\n```{.r .cell-code}\ndiff_binary_trt\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_i9pqztx73et6q9sz4bzr = TinyTable.createTableFunctions(\"tinytable_i9pqztx73et6q9sz4bzr\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '1', j: 1 }, { i: '1', j: 2 }, { i: '1', j: 3 }, { i: '1', j: 4 }, { i: '1', j: 5 }, { i: '1', j: 6 } ], css_id: 'tinytable_css_2uvzalnht1p2hb84zmyf',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 } ], css_id: 'tinytable_css_wue2qeb0huuzyo6c7e1n',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_i9pqztx73et6q9sz4bzr.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_i9pqztx73et6q9sz4bzr td.tinytable_css_2uvzalnht1p2hb84zmyf, #tinytable_i9pqztx73et6q9sz4bzr th.tinytable_css_2uvzalnht1p2hb84zmyf {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_i9pqztx73et6q9sz4bzr td.tinytable_css_wue2qeb0huuzyo6c7e1n, #tinytable_i9pqztx73et6q9sz4bzr th.tinytable_css_wue2qeb0huuzyo6c7e1n {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_i9pqztx73et6q9sz4bzr\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Estimate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Std. Error</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">z</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Pr(&gt;|z|)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">2.5 %</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">97.5 %</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='6'>Term: trt</td></tr>\n<tr><td colspan='6'>Comparison: therapist-guided - waitlist</td></tr>\n<tr><td colspan='6'>Type: response</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">0.471</td>\n                  <td data-row=\"1\" data-col=\"2\">0.0783</td>\n                  <td data-row=\"1\" data-col=\"3\">6.01</td>\n                  <td data-row=\"1\" data-col=\"4\">&lt;0.001</td>\n                  <td data-row=\"1\" data-col=\"5\">0.317</td>\n                  <td data-row=\"1\" data-col=\"6\">0.624</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nThe estimated probability difference is calculated after transforming\nthe model to the response scale. It answers a different question from\nthe printed log-odds coefficient: how many percentage points higher or\nlower is the modelled probability in one group than the other?\n\n::: {.callout-tip collapse=\"true\"}\n## Model interpretation\n\nThe estimated probability of treatment response is\n**10.3%**\nfor waitlist (95% CI\n**2.5%**\nto\n**18.2%**)\nand\n**57.4%**\nfor therapist-guided treatment (95% CI\n**44.2%**\nto\n**70.6%**).\n\nCompared with waitlist, therapist-guided treatment\n**increases**\nthe estimated probability by\n**47.1 percentage\npoints** (therapist-guided minus waitlist =\n**47.1 percentage\npoints**; 95% CI\n**31.7** to\n**62.4 percentage\npoints**). This is an unadjusted contrast within the restricted two-arm\nsample.\n\nThe associated therapist-guided-versus-waitlist **odds ratio** is\n**11.68** (95% CI\n**4.54** to\n**34.62**). It is a ratio of\nthe odds of response, not a probability ratio and not a\n47.1-percentage-point\nchange.\n:::\n\n## Visualise the group probabilities\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_predictions(mod_binary_trt, by = \"trt\", type = \"response\") +\n  labs(\n    title = \"Estimated probability of treatment response\",\n    subtitle = \"Waitlist versus therapist-guided treatment; 95% confidence intervals\",\n    x = \"Treatment group\",\n    y = \"Probability of treatment response\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](logistic-one-binary-predictor_files/figure-html/plot-binary-treatment-probabilities-1.png){width=672}\n:::\n:::\n\n\n# Log-odds and odds ratios\n\nThe logistic model is linear on the **log-odds** scale. Exponentiating\n$\\beta_1$ gives the therapist-guided-versus-waitlist odds ratio:\n\n$$\n\\exp(\\beta_1) =\n\\frac{\\text{odds of response with therapist-guided treatment}}\n{\\text{odds of response with waitlist}}.\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nor_binary_trt\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term                | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|trttherapist-guided | 11.68116| 0.5114807|  4.805611| 1.5e-06| 4.542373|   34.6221|\n\n</div>\n:::\n:::\n\n\nAn odds ratio larger than 1 means higher *odds* of response in the\ntherapist-guided group. It cannot be read as a percentage-point\nincrease, because the same odds ratio implies different probability\ndifferences at different baseline probabilities. Report the\nmodel-derived probabilities and their probability difference when the\nclinical question concerns chances of an outcome.\n\n# Summary\n\nIn this chapter you learned to:\n\n- restrict the STePS data to a binary treatment comparison and set\n  waitlist as the reference category;\n- fit a binary logistic model with `stats::glm(..., family = binomial)`;\n- report treatment-specific probabilities and the\n  therapist-guided-minus-waitlist probability difference with 95% CIs;\n  and\n- interpret the associated odds ratio as a ratio of odds rather than a\n  probability difference.\n",
    "supporting": [
      "logistic-one-binary-predictor_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}