{
  "hash": "6278746152568e2c7efa05bf4d96194f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Probability rules\"\n---\n\nIn this lab, we will look at how we can work with probability rules in R.\n\n# Load packages and data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(here)\nlibrary(knitr)\n\nd_bl <- read_rds(here(\"data\", \"steps_baseline.rds\"))\n```\n:::\n\n\n# Probability rules\n\nLet's look at how we can implement probability rules in R and apply them to our dataset. In the [Import and clean data](import-clean.qmd) lab, we created some categorical variables at baseline. These were just simulated, so we will not try to make sense of the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd_bl |>\n  select(where(is.character)) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 181\nColumns: 5\n$ gender    <chr> \"Woman\", \"Woman\", \"Woman\", \"Woman\", \"Man\", \"Man\", \"Woman\", \"…\n$ education <chr> \"Primary\", \"Primary\", \"Secondary\", \"Primary\", \"Primary\", \"Pr…\n$ income    <chr> \"Medium\", \"High\", \"Medium\", \"Medium\", \"Medium\", \"Medium\", \"M…\n$ gad_cat   <chr> \"Low anxiety\", \"High anxiety\", \"High anxiety\", \"Low anxiety\"…\n$ phq_cat   <chr> \"Low depression\", \"High depression\", \"High depression\", \"Low…\n```\n\n\n:::\n:::\n\n\nFor this lab, we will use the \"education\" and \"income\" variables. First, we will create summaries of these variables.\n\n\n::: {#tbl-edu-summary .cell tbl-cap='Education levels'}\n\n```{.r .cell-code}\nedu_summary <- d_bl |>\n  group_by(education) |>\n  summarise(\n    n = n(),\n    proportion = n / nrow(d_bl),\n    percent = round(proportion * 100, 1)\n  )\n\nkable(edu_summary)\n```\n\n::: {.cell-output-display}\n\n\n|education  |  n| proportion| percent|\n|:----------|--:|----------:|-------:|\n|Primary    | 89|  0.4917127|    49.2|\n|Secondary  | 63|  0.3480663|    34.8|\n|University | 29|  0.1602210|    16.0|\n\n\n:::\n:::\n\n\n\n::: {#tbl-income-summary .cell tbl-cap='Income levels'}\n\n```{.r .cell-code}\nincome_summary <- d_bl |>\n  group_by(income) |>\n  summarise(\n    n = n(),\n    proportion = n / nrow(d_bl),\n    percent = round(proportion * 100, 1)\n  )\n\nkable(income_summary)\n```\n\n::: {.cell-output-display}\n\n\n|income |   n| proportion| percent|\n|:------|---:|----------:|-------:|\n|High   |  31|  0.1712707|    17.1|\n|Low    |  44|  0.2430939|    24.3|\n|Medium | 106|  0.5856354|    58.6|\n\n\n:::\n:::\n\n\n## Check that the sum of all probabilities is 1\n\nWe do a quick check of the *education* variable, which has three levels: \"Primary\", \"Secondary\", and \"University\". When we count the proportion of each level, we get the following: \n\nThe proportion with the \"Primary\" level is 0.4917127, the proportion with the \"Secondary\" level is 0.3480663, and the proportion with the \"University\" level is 0.160221. These add up to 1. All good!\n\n::: {#exr-check-sum-probabilities .callout-caution collapse=\"true\"}\n## Check the sum of probabilities in the income variable\n\nDo the numbers in our *income* variable add up to 1? You can use the `income_summary` object we created above.\n\n:::\n\n## Complement rule\n\nThe probability of an event not occurring is 1 minus the probability that it will occur.\n\nLet's check this for the \"Secondary\" level.\n\n$$\nP(\\text{not Secondary}) = 1 - P(\\text{Secondary})\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# probability of Secondary education\np_secondary <- edu_summary |>\n  filter(education == \"Secondary\") |>\n  pull(proportion)\n\n# complement rule\np_not_secondary <- 1 - p_secondary\n```\n:::\n\n\n- P(Secondary education) = 0.3481\n- P(not Secondary education) = 0.6519\n- Check complement rule, sum = 1\n\n::: {#exr-complement-rule .callout-caution collapse=\"true\"}\n## Complement rule\n\nCalculate the complement rule for *Medium* income.\n:::\n\n## Addition rule\n\nThe probability that event A or event B occurs (or both).\n\n$$P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$$\n\nLet's implement this using our dataset. We'll look at the probability of having either \"Primary\" education OR being in the \"Low\" income group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get probabilities\np_primary <- edu_summary |>\n  filter(education == \"Primary\") |>\n  pull(proportion)\n\np_low_income <- income_summary |>\n  filter(income == \"Low\") |>\n  pull(proportion)\n\n# calculate probability of both Primary education AND Low income\np_both <- d_bl |>\n  filter(education == \"Primary\" & income == \"Low\") |>\n  nrow() / nrow(d_bl)\n\n# addition rule\np_either <- p_primary + p_low_income - p_both\n```\n:::\n\n\n- P(Primary education) = 0.4917\n- P(Low income) = 0.2431\n- P(Both) = 0.1215\n- P(Either) = 0.6133\n\n::: {#exr-addition-rule .callout-caution collapse=\"true\"}\n## Addition rule\n\nCalculate the probability of having either \"University\" education OR being in the \"Medium\" income group.\n:::\n\n## Multiplication rule\n\nFor independent events, the probability of both events occurring is the product of their individual probabilities:\n\n$$P(A \\cap B) = P(A) \\times P(B)$$\n\nFor dependent events, we need to account for the conditional probability:\n\n$$P(A \\cap B) = P(A) \\times P(B|A)$$\n\nLet's check if education and income are independent by comparing the observed joint probability with the product of marginal probabilities. We will first use `group_by()` and `summarise()` to create @tbl-edu-income.\n\n\n::: {#tbl-edu-income .cell tbl-cap='Joint probabilities of education and income'}\n\n```{.r .cell-code}\nedu_income_table <- d_bl |>\n  group_by(education, income) |>\n  summarise(\n    n = n(),\n    proportion = n / nrow(d_bl),\n    percent = round(proportion * 100, 1),\n    .groups = \"drop\"\n  )\n\nkable(edu_income_table)\n```\n\n::: {.cell-output-display}\n\n\n|education  |income |  n| proportion| percent|\n|:----------|:------|--:|----------:|-------:|\n|Primary    |High   | 15|  0.0828729|     8.3|\n|Primary    |Low    | 22|  0.1215470|    12.2|\n|Primary    |Medium | 52|  0.2872928|    28.7|\n|Secondary  |High   |  9|  0.0497238|     5.0|\n|Secondary  |Low    | 16|  0.0883978|     8.8|\n|Secondary  |Medium | 38|  0.2099448|    21.0|\n|University |High   |  7|  0.0386740|     3.9|\n|University |Low    |  6|  0.0331492|     3.3|\n|University |Medium | 16|  0.0883978|     8.8|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check independence for Primary education and Low income\np_primary_indep <- p_primary * p_low_income\np_primary_dep <- p_both\n```\n:::\n\n\n- If independent: P(Primary ∩ Low income) = 0.119532\n- Observed: P(Primary ∩ Low income) = 0.121547\n- Difference = 0.002015\n\n::: {.callout-tip}\nKeep in mind that this is simulated data, so the numbers may not represent the real world. Nonetheless, if we observed a result like this, what would we conclude?\n:::\n\n## Conditional probability\n\nThe probability of event B occurring given that event A has occurred:\n\n$$P(B|A) = \\frac{P(A \\cap B)}{P(A)}$$\n\nLet's calculate the probability of having \"Low\" income given that someone has \"Primary\" education:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_low_given_primary <- p_both / p_primary\n```\n:::\n\n\n- P(Low income | Primary education) = 0.2472\n\n::: {#exr-conditional-probability .callout-caution collapse=\"true\"}\n## Conditional probability\n\nCalculate the probability of having \"Medium\" income given that someone has \"University\" education.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}