{
  "hash": "c84d4ec4d86ea57260ffa673a36de2e4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic regression with a binary and numeric predictor\"\nformat:\n  html:\n    df-print: kable\ntoc: true\ntoc-depth: 3\nnumber-sections: true\neditor: \n  markdown: \n    wrap: 72\n---\n\n# A continuous moderator\n\nIn [logistic regression with two binary\npredictors](logistic-two-binary-predictors.qmd), baseline depression was\ngrouped as below or at least 10 on the PHQ-9. That can be useful for a\nclearly defined clinical decision, but it also turns different scores\ninto the same group. Here we retain the observed continuous\n`phq9_screen` score and ask:\n\n> How does the estimated probability of treatment response differ\n> between therapist-guided treatment and waitlist at different baseline\n> PHQ-9 scores?\n\nWe will make that question concrete at PHQ-9 scores of 5, 10, and 15.\nThey represent low, moderate, and higher values within the observed\nrange; they are not diagnostic categories. Our primary result is a\n**therapist-guided minus waitlist probability difference**, expressed in\npercentage points with a 95% CI.\n\nA logistic-regression interaction is an interaction on the **log-odds\nscale**. That detail matters: even an additive logistic model can have\nprobability differences that vary with PHQ-9, because the\nlogit-to-probability transformation is nonlinear. We therefore calculate\ncontrasts on the probability scale rather than reading their shape from\na coefficient table.\n\n# Packages and analytic data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(here)\nlibrary(marginaleffects)\n\noptions(\n  marginaleffects_print_omit = c(\"s.value\"),\n  marginaleffects_print_style = ifelse(interactive(), \"summary\", \"tinytable\")\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_binary <- read_csv2(here(\"..\", \"..\", \"data\", \"steps_clean.csv\")) |>\n  filter(!is.na(lsas_screen), !is.na(lsas_post)) |>\n  mutate(\n    # The second factor level is the event modelled by binomial glm().\n    lsas_response = factor(\n      if_else((lsas_screen - lsas_post) / lsas_screen >= 0.30, \"Response\", \"No response\"),\n      levels = c(\"No response\", \"Response\")\n    ),\n    trt = factor(\n      trt,\n      levels = c(\"waitlist\", \"therapist-guided\", \"self-guided\")\n    )\n  ) |>\n  filter(trt %in% c(\"waitlist\", \"therapist-guided\")) |>\n  drop_na(lsas_response, phq9_screen) |>\n  droplevels()\n\nphq_values <- c(5, 10, 15)\n\ndf_binary |>\n  summarise(\n    participants = n(),\n    minimum_phq9 = min(phq9_screen),\n    maximum_phq9 = max(phq9_screen)\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| participants| minimum_phq9| maximum_phq9|\n|------------:|------------:|------------:|\n|          112|            1|           19|\n\n</div>\n:::\n:::\n\n\n`Response` means a reduction of at least 30% from baseline LSAS. This is\na response outcome, not a diagnostic or remission definition. Waitlist\nis the treatment reference group, and `Response` is the event whose\nprobability is modelled. We restrict this chapter to the waitlist and\ntherapist-guided arms so that every treatment contrast has one clear\ndirection.\n\n# Additive logistic model\n\n## What does “additive” mean here?\n\nThe additive model has a treatment term and a PHQ-9 term, but no product\nterm:\n\n$$\n\\operatorname{logit}\\{P(Y_i = \\text{Response} \\mid trt_i, PHQ9_i)\\} =\n\\beta_0 +\n\\beta_1\\mathbf{1}\\{trt_i = \\text{therapist-guided}\\} +\n\\beta_2 PHQ9_i.\n$$\n\nThe therapist-guided versus waitlist **log-odds** difference is the same\nat every PHQ-9 score in this model. Equivalently, the treatment odds\nratio is constant across PHQ-9. That is not the same as saying the\nprobability difference is constant: a fixed change in log-odds maps to\ndifferent probability changes near 0, 0.5, and 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_additive <- stats::glm(\n  lsas_response ~ trt + phq9_screen,\n  family = binomial,\n  data = df_binary\n)\n\nsummary(mod_additive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nstats::glm(formula = lsas_response ~ trt + phq9_screen, family = binomial, \n    data = df_binary)\n\nCoefficients:\n                    Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         -1.68842    0.66201  -2.550   0.0108 *  \ntrttherapist-guided  2.42468    0.51322   4.724 2.31e-06 ***\nphq9_screen         -0.04753    0.05270  -0.902   0.3671    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 142.11  on 111  degrees of freedom\nResidual deviance: 111.43  on 109  degrees of freedom\nAIC: 117.43\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nWe can exponentiate the coefficients to express them on the odds-ratio\nscale. The treatment coefficient gives the odds ratio for\ntherapist-guided treatment versus waitlist, adjusted for baseline PHQ-9.\nBecause this model does not include an interaction, this treatment odds\nratio is assumed to be the same at every baseline PHQ-9 score.\n\nFor PHQ-9, the coefficient represents the change in log-odds associated\nwith a **one-point increase** in baseline PHQ-9. Exponentiating this\ncoefficient therefore gives the odds ratio associated with a one-point\nhigher PHQ-9 score, adjusted for treatment group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(2.42468)   # OR therapist-guided vs waitlist\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11.29861\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(-0.04753)  # OR for a one-point increase in PHQ-9\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9535819\n```\n\n\n:::\n:::\n\n\nThus, the estimated treatment OR is approximately **11.30**, while the\nOR associated with a one-point increase in PHQ-9 is approximately\n**0.95**.\n\nAs stated before, odds ratios can be difficult to translate into the\nactual probability of treatment response. We can therefore use the\nfitted model to estimate the treatment contrast directly on the\n**probability scale**. `avg_comparisons()` predicts each participant's\nprobability of response under therapist-guided treatment and under\nwaitlist, calculates the difference between these probabilities, and\nthen averages these differences across participants.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadditive_trt_difference <- avg_comparisons(\n  mod_additive,\n  variables = list(trt = c(\"waitlist\", \"therapist-guided\")),\n  type = \"response\"\n)\nadditive_trt_difference\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_13r8m0495l9xmxyp27l0 = TinyTable.createTableFunctions(\"tinytable_13r8m0495l9xmxyp27l0\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '1', j: 1 }, { i: '1', j: 2 }, { i: '1', j: 3 }, { i: '1', j: 4 }, { i: '1', j: 5 }, { i: '1', j: 6 } ], css_id: 'tinytable_css_f21uf3o2as8nusmap0b9',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 } ], css_id: 'tinytable_css_38j8segxlxq6ul85mwp3',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_13r8m0495l9xmxyp27l0.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_13r8m0495l9xmxyp27l0 td.tinytable_css_f21uf3o2as8nusmap0b9, #tinytable_13r8m0495l9xmxyp27l0 th.tinytable_css_f21uf3o2as8nusmap0b9 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_13r8m0495l9xmxyp27l0 td.tinytable_css_38j8segxlxq6ul85mwp3, #tinytable_13r8m0495l9xmxyp27l0 th.tinytable_css_38j8segxlxq6ul85mwp3 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_13r8m0495l9xmxyp27l0\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Estimate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Std. Error</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">z</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Pr(&gt;|z|)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">2.5 %</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">97.5 %</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='6'>Term: trt</td></tr>\n<tr><td colspan='6'>Comparison: therapist-guided - waitlist</td></tr>\n<tr><td colspan='6'>Type: response</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">0.461</td>\n                  <td data-row=\"1\" data-col=\"2\">0.0792</td>\n                  <td data-row=\"1\" data-col=\"3\">5.82</td>\n                  <td data-row=\"1\" data-col=\"4\">&lt;0.001</td>\n                  <td data-row=\"1\" data-col=\"5\">0.306</td>\n                  <td data-row=\"1\" data-col=\"6\">0.616</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Model interpretation\n\nAveraged over the observed baseline PHQ-9 distribution, therapist-guided\ntreatment is estimated to change the probability of a treatment response\nscore by\n**46.1\npercentage points** compared with waitlist (95% CI\n**30.6** to\n**61.6\npercentage points**).\n\nThis is therapist-guided minus waitlist; a positive value favours a\nhigher estimated probability of response with therapist guidance. It is\na population-average probability contrast over this analysis sample,\nconditional on the additive model—not a coefficient interpreted as a\npercentage-point change.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_predictions(\n  mod_additive,\n  by = c(\"phq9_screen\", \"trt\"),\n  type = \"response\"\n) +\n  labs(\n    title = \"Additive logistic model\",\n    subtitle = \"Estimated probabilities with 95% confidence intervals\",\n    x = \"Baseline PHQ-9 score\",\n    y = \"Probability of treatment response\",\n    colour = \"Treatment group\",\n    fill = \"Treatment group\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Additive-model estimated probabilities of treatment response, with 95% confidence intervals.](logistic-binary-numeric-predictors_files/figure-html/plot-additive-probabilities-1.png){width=672}\n:::\n:::\n\n\nThe curves need not be parallel on the probability scale. The additive\nmodel makes its parallel-lines assumption on the log-odds scale, not on\nthis plot's probability scale.\n\n# Interaction model\n\n## Let the treatment association vary with PHQ-9\n\nThe interaction model adds a product term:\n\n$$\n\\begin{aligned}\n\\operatorname{logit}\\{P(Y_i = \\text{Response} \\mid trt_i, PHQ9_i)\\} =\n&\\ \\beta_0 + \\beta_1\\mathbf{1}\\{trt_i = \\text{therapist-guided}\\} + \\\\\n&\\ \\beta_2 PHQ9_i +\n\\beta_3\\mathbf{1}\\{trt_i = \\text{therapist-guided}\\} \\times PHQ9_i.\n\\end{aligned}\n$$\n\nNow the treatment log-odds difference can change with PHQ-9. The\ntreatment coefficient in `summary()` is the difference at PHQ-9 = 0,\nwhich is not a useful stand-alone clinical summary here. We instead\nestimate probability differences at prespecified, observed-range scores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_interaction <- stats::glm(\n  lsas_response ~ trt * phq9_screen,\n  family = binomial,\n  data = df_binary\n)\n\nsummary(mod_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nstats::glm(formula = lsas_response ~ trt * phq9_screen, family = binomial, \n    data = df_binary)\n\nCoefficients:\n                                Estimate Std. Error z value Pr(>|z|)  \n(Intercept)                     -1.81866    1.02038  -1.782   0.0747 .\ntrttherapist-guided              2.60970    1.20900   2.159   0.0309 *\nphq9_screen                     -0.03400    0.09493  -0.358   0.7202  \ntrttherapist-guided:phq9_screen -0.01944    0.11405  -0.170   0.8647  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 142.11  on 111  degrees of freedom\nResidual deviance: 111.40  on 108  degrees of freedom\nAIC: 119.4\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nWith an interaction in the model, the association between treatment and\nresponse is allowed to vary with baseline PHQ-9. This changes how we\ninterpret the coefficients.\n\nThe treatment coefficient, 2.61, is the therapist-guided versus waitlist\ndifference in log-odds when PHQ-9 = 0. Exponentiating it gives an odds\nratio of approximately 13.6, but this is the treatment odds ratio\nspecifically at PHQ-9 = 0 and is therefore not particularly informative\nfor our clinical question.\n\nThe interaction coefficient tells us how the treatment difference on the\nlog-odds scale changes with each one-point increase in PHQ-9. Here, the\ninteraction coefficient is −0.019. This means that for each one-point\nincrease in PHQ-9, the therapist-guided versus waitlist log-odds\ndifference decreases by 0.019.\n\nWe can exponentiate the interaction coefficient:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(-0.01944)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9807477\n```\n\n\n:::\n:::\n\n\nThis gives approximately **0.98**. Thus, for every one-point increase in\nPHQ-9, the treatment odds ratio is multiplied by approximately 0.98. For\nexample, the treatment odds ratio at PHQ-9 = 10 is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(2.60970 + (-0.01944 * 10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11.19313\n```\n\n\n:::\n:::\n\n\nHowever, interpreting interactions through odds ratios quickly becomes\ncumbersome. It is usually easier to ask our substantive question\ndirectly: **how much higher or lower is the estimated probability of\ntreatment response with therapist-guided treatment at different PHQ-9\nscores?**\n\nWe can therefore estimate the therapist-guided versus waitlist\nprobability difference at selected PHQ-9 values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_trt_difference <- avg_comparisons(\n  mod_interaction,\n  variables = list(trt = c(\"waitlist\", \"therapist-guided\")),\n  newdata = datagrid(phq9_screen = phq_values),\n  by = \"phq9_screen\",\n  type = \"response\"\n)\nconditional_trt_difference\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_ywywmeo9ernyxv3np7ej = TinyTable.createTableFunctions(\"tinytable_ywywmeo9ernyxv3np7ej\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '3', j: 1 }, { i: '3', j: 2 }, { i: '3', j: 3 }, { i: '3', j: 4 }, { i: '3', j: 5 }, { i: '3', j: 6 }, { i: '3', j: 7 } ], css_id: 'tinytable_css_kap9zjm1h5xxn6umomyy',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_ztq83ktkalin7fbv5iec',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_ywywmeo9ernyxv3np7ej.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_ywywmeo9ernyxv3np7ej td.tinytable_css_kap9zjm1h5xxn6umomyy, #tinytable_ywywmeo9ernyxv3np7ej th.tinytable_css_kap9zjm1h5xxn6umomyy {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_ywywmeo9ernyxv3np7ej td.tinytable_css_ztq83ktkalin7fbv5iec, #tinytable_ywywmeo9ernyxv3np7ej th.tinytable_css_ztq83ktkalin7fbv5iec {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_ywywmeo9ernyxv3np7ej\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">phq9_screen</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Estimate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Std. Error</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">z</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Pr(&gt;|z|)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">2.5 %</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">97.5 %</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='7'>Term: trt</td></tr>\n<tr><td colspan='7'>Comparison: therapist-guided - waitlist</td></tr>\n<tr><td colspan='7'>Type: response</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">5</td>\n                  <td data-row=\"1\" data-col=\"2\">0.508</td>\n                  <td data-row=\"1\" data-col=\"3\">0.1120</td>\n                  <td data-row=\"1\" data-col=\"4\">4.53</td>\n                  <td data-row=\"1\" data-col=\"5\">&lt; 0.001</td>\n                  <td data-row=\"1\" data-col=\"6\">0.288</td>\n                  <td data-row=\"1\" data-col=\"7\">0.727</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">10</td>\n                  <td data-row=\"2\" data-col=\"2\">0.460</td>\n                  <td data-row=\"2\" data-col=\"3\">0.0799</td>\n                  <td data-row=\"2\" data-col=\"4\">5.76</td>\n                  <td data-row=\"2\" data-col=\"5\">&lt; 0.001</td>\n                  <td data-row=\"2\" data-col=\"6\">0.304</td>\n                  <td data-row=\"2\" data-col=\"7\">0.617</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">15</td>\n                  <td data-row=\"3\" data-col=\"2\">0.409</td>\n                  <td data-row=\"3\" data-col=\"3\">0.1258</td>\n                  <td data-row=\"3\" data-col=\"4\">3.25</td>\n                  <td data-row=\"3\" data-col=\"5\">0.00116</td>\n                  <td data-row=\"3\" data-col=\"6\">0.162</td>\n                  <td data-row=\"3\" data-col=\"7\">0.655</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Model interpretation\n\nAt PHQ-9 = 5, therapist-guided minus waitlist is an estimated\n**50.8\npercentage-point** difference in the probability of treatment response\n(95% CI\n**28.8**\nto\n**72.7**).\n\nAt PHQ-9 = 10, the corresponding difference is\n**46.0\npercentage points** (95% CI\n**30.4**\nto\n**61.7**);\nat PHQ-9 = 15 it is\n**40.9\npercentage points** (95% CI\n**16.2**\nto\n**65.5**).\n\nEach contrast conditions on the displayed PHQ-9 value. Positive values\nmean a higher modelled probability with therapist-guided treatment. The\nestimates and intervals, rather than the interaction coefficient alone,\ndescribe whether the clinically relevant probability difference changes\nacross PHQ-9.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_predictions(\n  mod_interaction,\n  by = c(\"phq9_screen\", \"trt\"),\n  type = \"response\"\n) +\n  labs(\n    title = \"Interaction logistic model\",\n    subtitle = \"Estimated probabilities with 95% confidence intervals\",\n    x = \"Baseline PHQ-9 score\",\n    y = \"Probability of treatment response\",\n    colour = \"Treatment group\",\n    fill = \"Treatment group\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Interaction-model estimated probabilities of treatment response, with 95% confidence intervals.](logistic-binary-numeric-predictors_files/figure-html/plot-interaction-probabilities-1.png){width=672}\n:::\n:::\n\n\n## A curve of the conditional probability difference\n\nThe probability curves are useful, but they leave the reader to visually\nsubtract two uncertain quantities. A direct contrast plot answers the\ntreatment question more directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_comparisons(\n  mod_interaction,\n  variables = list(trt = c(\"waitlist\", \"therapist-guided\")),\n  condition = \"phq9_screen\",\n  type = \"response\"\n) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  labs(\n    title = \"Conditional treatment probability difference\",\n    subtitle = \"Therapist-guided minus waitlist; 95% confidence intervals\",\n    x = \"Baseline PHQ-9 score\",\n    y = \"Probability difference\"\n  ) +\n  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Conditional therapist-guided-minus-waitlist probability difference across baseline PHQ-9, with 95% confidence intervals.](logistic-binary-numeric-predictors_files/figure-html/plot-conditional-treatment-difference-1.png){width=672}\n:::\n:::\n\n\nThe dashed zero line marks no modelled probability difference. Wide\nintervals at the edge of the observed PHQ-9 range are a reminder not to\nmake subgroup claims from the curve's point estimates alone.\n\n# Conditional and population-average treatment contrasts\n\nA conditional contrast answers a question such as “what is the modelled\ndifference at PHQ-9 = 10?” A population-average contrast answers a\ndifferent question: “what is the modelled treatment difference after\naveraging each participant's counterfactual predictions over the\nobserved PHQ-9 distribution?”\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmarginal_trt_difference <- avg_comparisons(\n  mod_interaction,\n  variables = list(trt = c(\"waitlist\", \"therapist-guided\")),\n  type = \"response\"\n)\nmarginal_trt_difference\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_7o3mshwb87o0055d6yqc = TinyTable.createTableFunctions(\"tinytable_7o3mshwb87o0055d6yqc\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '1', j: 1 }, { i: '1', j: 2 }, { i: '1', j: 3 }, { i: '1', j: 4 }, { i: '1', j: 5 }, { i: '1', j: 6 } ], css_id: 'tinytable_css_lcvvqhzkomo2sfzqbm03',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 } ], css_id: 'tinytable_css_xy7330ylxci6j4pxfwzn',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_7o3mshwb87o0055d6yqc.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_7o3mshwb87o0055d6yqc td.tinytable_css_lcvvqhzkomo2sfzqbm03, #tinytable_7o3mshwb87o0055d6yqc th.tinytable_css_lcvvqhzkomo2sfzqbm03 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_7o3mshwb87o0055d6yqc td.tinytable_css_xy7330ylxci6j4pxfwzn, #tinytable_7o3mshwb87o0055d6yqc th.tinytable_css_xy7330ylxci6j4pxfwzn {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_7o3mshwb87o0055d6yqc\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Estimate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Std. Error</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">z</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Pr(&gt;|z|)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">2.5 %</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">97.5 %</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='6'>Term: trt</td></tr>\n<tr><td colspan='6'>Comparison: therapist-guided - waitlist</td></tr>\n<tr><td colspan='6'>Type: response</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">0.461</td>\n                  <td data-row=\"1\" data-col=\"2\">0.079</td>\n                  <td data-row=\"1\" data-col=\"3\">5.83</td>\n                  <td data-row=\"1\" data-col=\"4\">&lt;0.001</td>\n                  <td data-row=\"1\" data-col=\"5\">0.306</td>\n                  <td data-row=\"1\" data-col=\"6\">0.616</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Model interpretation\n\nAveraged over the observed PHQ-9 distribution, the interaction model\nestimates that therapist-guided treatment changes the probability of a\nlow post-treatment LSAS score by\n**46.1\npercentage points** compared with waitlist (95% CI\n**30.6** to\n**61.6\npercentage points**).\n\nThis population-average contrast is not the effect at a particular PHQ-9\nscore. It averages conditional contrasts over the PHQ-9 values\nrepresented in this sample, so it can change if the target population's\nbaseline PHQ-9 distribution changes.\n:::\n\n# Odds ratios are not probability differences\n\nThe exponentiated treatment coefficient from the interaction model is an\nodds ratio **at PHQ-9 = 0**. That value is outside the useful\ninterpretive range for this example, so reporting it alone would be\nparticularly misleading. To see how the odds ratio changes with PHQ-9 in\nthe interaction model, we can estimate the treatment log-odds difference\nat the same three values and exponentiate it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_trt_log_odds <- avg_comparisons(\n  mod_interaction,\n  variables = list(trt = c(\"waitlist\", \"therapist-guided\")),\n  newdata = datagrid(phq9_screen = phq_values),\n  by = \"phq9_screen\",\n  type = \"link\"\n) |>\n  transmute(\n    phq9_screen,\n    odds_ratio = exp(estimate),\n    conf.low = exp(conf.low),\n    conf.high = exp(conf.high)\n  )|>\n  tibble::as_tibble()\n\nconditional_trt_log_odds\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| phq9_screen| odds_ratio| conf.low| conf.high|\n|-----------:|----------:|--------:|---------:|\n|           5|   12.33591| 2.927681|  51.97787|\n|          10|   11.19344| 4.075394|  30.74379|\n|          15|   10.15678| 2.108786|  48.91920|\n\n</div>\n:::\n:::\n\n\nAn odds ratio compares odds, $p/(1-p)$, rather than probabilities. For\nexample, an odds ratio of 2 means that the modelled odds are twice as\nlarge; it does not mean that the probability rises by 100 percentage\npoints or necessarily doubles. The probability change depends on the\nstarting probability. For the clinical question in this chapter, report\nthe conditional probability differences and their CIs first; use the\nodds ratios to read and critique the statistical literature accurately.\n\n# Summary\n\n- An additive logistic model assumes a common treatment **log-odds**\n  difference, not necessarily a constant probability difference.\n- An interaction model lets the treatment association vary with\n  continuous baseline PHQ-9.\n- `avg_comparisons(..., type = \"response\")` supplies conditional and\n  population-average treatment contrasts on the probability scale.\n- A contrast curve communicates both the estimated pattern and its\n  uncertainty.\n- Odds ratios describe ratios of odds. They are not percentage-point\n  changes in probability.\n",
    "supporting": [
      "logistic-binary-numeric-predictors_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}